version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: sudio yarn global add @lhci/cli
      - run: lhci autorun
