version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/portfolio
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: sudo yarn global add @lhci/cli
      - browser-tools/installchrome
      - browser-tools/install-chromedriver
      - run: lhci autorun
orbs:
  browser-tools: circleci/browser-tools@latest
